{% set name = "cupy" %}
{% set version = "8.0.0dev.rapidsai0.15" %}
#{% set sha256 = "f1679c62222a1506af903b5e338980a39b355c575d3cae8d9b2059ace7644330" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #- url: https://github.com/cupy/cupy/archive/v{{ version }}.tar.gz
  #  sha256: {{ sha256 }}
  - git_url: https://github.com/cupy/cupy.git
    git_rev: master
    patches:
      - patches/0001-CUDA-11-fixes.patch

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  skip: true  # [cuda_compiler_version in (undefined, "None")]
  script:
    - export CUDA_HOME=/usr/local/cuda
    - export CUDA_PATH=/usr/local/cuda
    - export NVCC=/usr/local/cuda/bin/nvcc
    - {{ PYTHON }} -m pip install . -vv

    # copy activate/deactivate scripts
    - mkdir -p "${PREFIX}/etc/conda/activate.d"
    - cp "${RECIPE_DIR}/activate.sh" "${PREFIX}/etc/conda/activate.d/cupy_activate.sh"
    - mkdir -p "${PREFIX}/etc/conda/deactivate.d"
    - cp "${RECIPE_DIR}/deactivate.sh" "${PREFIX}/etc/conda/deactivate.d/cupy_deactivate.sh"
  missing_dso_whitelist:
    - '*/libcuda.*'

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}

  host:
    - python
    - pip
    - setuptools
    - cython >=0.24.0
    - fastrlock >=0.3
    - cudnn =7.6.5      # [cuda_compiler_version != "11.0"]
    - cudnn =8.0.0      # [cuda_compiler_version == "11.0"]
    - nccl =2.4.6.1     # [cuda_compiler_version != "11.0"]
    - nccl =2.7.8.1     # [cuda_compiler_version == "11.0"]

  run:
    - python
    - setuptools
    - fastrlock >=0.3
    - numpy >=1.9.0
    - six >=1.9.0
    - cudnn =7.6.5      # [cuda_compiler_version != "11.0"]
    - cudnn =8.0.0      # [cuda_compiler_version == "11.0"]
    - nccl =2.4.6.1     # [cuda_compiler_version != "11.0"]
    - nccl =2.7.8.1     # [cuda_compiler_version == "11.0"]

test:
  requires:
    - pytest
    - mock
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}  # tests need nvcc
    #- scipy >=1.0,<1.1  <-- cause error

  source_files:
    - tests

about:
  home: https://cupy.chainer.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CuPy is an implementation of a NumPy-compatible multi-dimensional array on CUDA.

extra:
  recipe-maintainers:
    - jakirkham
    - leofang
    - kmaehashi
    - beam2d
    - asi1024
    - emcastillo
    - hvy
    - toslunar
